### PR TITLE
Support exporting to SQL Server or a T-SQL script file.

### PR DESCRIPTION
**Pull request by kevingy**
Issue #6: Implement exporting to T-SQL

### CODE REVIEW

**Comment by UziTech** [comment]
Thanks for this. The code looks good. Ill see if I can setup a Domino server to test this.

**Comment by UziTech** [comment]
Can you clean up the dialog box a little bit.

- Set FormBorderStyle = `FixedDialog` so it isn't resizable and the icon doesn't show.
- Make the cancel button show the whole text.

image

**Comment by UziTech** [comment]
Also remove the minimize and maximize buttons

image

**Comment by kevingy** [comment]
All good suggestions. Here are the fixes.

**Comment by UziTech** [comment]
Thanks for this. I'll try to get a new release out soon.

**Comment by kevingy** [comment]
My pleasure!

**Pull request merged**
