### PR TITLE
replace "," in decimal type values TsqlGenerator.cs

### PR DESCRIPTION
**Pull request by onkelbecky**

### CODE REVIEW

**Comment by UziTech** [comment]
Are the decimal types in German? Is there another way to change the language?

**Comment by onkelbecky** [comment]
> Are the decimal types in German?

yes "," is the decimaltype in germany. the problem is, its also the column-separator and you get an error because there are more fields than in the mapping

f.e:

insert into dummy (sometext, somedouble) values ("some text value", 3,4)


> Is there another way to change the language?


somewhere after the convertion from string to number in the tsql part and the string concatination to the outputstring must go wrong. maby because of the language setting in the os. i dont know...

i think this will get rid of any error caused by language types.

my sql server also had problems with the datetimestring "2022-12-31 12:00:00" ang goes "out of range" while the input.
i think my server expects the english format "2022-31-12" i dont know exaktly and why.

in another commit i replaced the "yyyy-MM-dd" with "yyyyMMdd" to fix it.

but im not done whith any error comming to my project and im still working on it.

**Comment by UziTech** [comment]
Is it possible to just quote the decimal like `insert into dummy (sometext, somedouble) values ("some text value", "3,4")` or to change the language before getting the value so it gets `3.4`?

**Comment by onkelbecky** [comment]
i will check both on monday.

**Comment by onkelbecky** [comment]
hey, meanwhile there are some commits for our purposes.
maby theres no need to merge...
you can check my fork and if theres some advanteges we can talk ;) or you cherrypick ;)

**Comment by UziTech** [comment]
Thanks, I will leave this as is. I do

**Comment by onkelbecky** [comment]
were about to leave lotus too. this is for data saving.
but for that this was really helpfull.
thank you very much for your work!

**Pull request closed without merging**
